### ISSUE TITLE
Possible to have two applications to the same scholarship

### ISSUE THREAD

**Issue by cg505** [WLCSC/scholarshipBook#1]
It's possible to open two applications to the same scholarship. Further compounding the issue is that there's no way to delete applications once they've been created.

**Comment by braddoeswebdev** [comment]
Do you know what you did to generate the second one?

**Comment by cg505** [comment]
Generate one application, hit browser back button, then generate another
application.

**Comment by braddoeswebdev** [comment]
Should be fixed now.  Added actual validation & better redirection in the controller.
